PROJECT_TYPE = eclipse_plugin
NONDEFAULT_SHIPPABLE_TARGETS_DEPENDENCY = .build_93k_plugin
SHIPPABLE_TARGETS = default

CLOBBER_FILES_LOCAL = \
                      src/com/example/itee/maint/common/FrameStrings.java \

GENERATED_EXT_SYMLINKS = \
   $(MODULE)/src/com/example/itee/maint/common/FrameStrings.java => \
   $(WORKSPACE)/maint/cor/Frame/Util/GenStringDefs/Main/FrameStrings.java \
   
